### ISSUE TITLE
When i run ./grailsw error is " Exception in thread "main" java.util.zip.ZipException: error in opening zip file "

### ISSUE THREAD

**Issue by ykarthikreddy18** [vishesh04/Filesutra#6]
I runned the ./grailsw, it is downloadedd 2.4.4 version but it is unable to open the zip file and i couldnt able to find any solution. I was strucked here. could you plz help?

**Comment by vishesh04** [comment]
Hi @ykarthikreddy18 , let's get on to a call where we can solve this problem. I will send you an invite.

**Comment by ykarthikreddy18** [comment]
Hi @vishesh04 . Is it known problem? .. I already had an app which is running on grails 2.3.9 .. I tried to install your application, but at ./grailsw im getting that error..

**Comment by ykarthikreddy18** [comment]
Hi @vishesh04 , Thanks problem is solved
